export const AMQPLIB_CONTROLLER_NAME = Symbol('AMQPLIB_CONTROLLER_NAME');

export const AMQPLIB_ACTION_NAME = Symbol('AMQPLIB_ACTION_NAME');

export const AMQPLIB_ACTION_TYPE = Symbol('AMQPLIB_ACTION_TYPE');

export const AMQPLIB_ACTION_PARAMS_INJECTIONS = Symbol('AMQPLIB_ACTION_PARAMS_INJECTIONS');
